CREATE DATABASE db_stepup;
USE db_stepup;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    nim VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS rewards (
    id_reward INT AUTO_INCREMENT PRIMARY KEY,
    nama_reward VARCHAR(255) NOT NULL,
    poin INT NOT NULL,
    gambar VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);